'''The Syracuse (also called Collatz or Hailstone) sequence is generated by starting with a nat- ural number and repeatedly applying the following function until reaching 1:
syr(x) = x/2 if x is even 
         3x+1 if x is odd

For example, the Syracuse sequence starting with 5 is: 5, 16, 8, 4, 2, 1. It is an open question in mathematics whether this sequence will always go to 1 for every possible starting value.
Write a program that gets a starting value from the user and then prints the Syracuse sequence for that starting value.'''
import subprocess
subprocess.run('reset')


def syracause():
    n = input("Enter starting value : ")
    print("The syracause sequence is : ")
    num = int(n)

    try:
        while(num != 1):
            print(num, end=", ")
            if(num % 2 == 0):
                num = num/2
            else:
                num = (3*num)+1
            # print 1 at last
        print(1)
    except:
        print("Sorry, I don't think this hits 1")


syracause()
